name: Docker Image

on: [push]
# on:
#   push:
#     branches: [os-checker]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/mirai:latest
  IMAGE_TAR: /tmp/mirai.tar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    ######## Local Image ########
    - name: Build Docker Image
      run: docker build -t test .

    - name: Run Docker Image
      run: docker run test "cat .github/ci/hello.sh"
    #############################

