name: Github API

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: gh api
        run: |
          which busybox || true
          gh auth status
          sh gh-api.sh
