name: arceos-apps

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    if: true
    strategy:
      fail-fast: false
      matrix:
        targets: ["aarch64-unknown-none", "riscv64gc-unknown-none-elf", "x86_64-unknown-none"]
    steps:
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets: ${{ matrix.targets }}
        components: clippy, rustfmt
    - uses: taiki-e/install-action@cargo-hack

    - run: rustup -Vv
    - run: rustc -Vv
    - run: cargo -Vv

    - uses: actions/checkout@v4
      with:
        repository: arceos-org/arceos-apps

    - name: display cargo build
      working-directory: rust/display
      run: cargo build --target ${{ matrix.targets }}

    - name: bwbench cargo build
      working-directory: rust/net/bwbench
      run: cargo build --target ${{ matrix.targets }}
