name: Docker

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    if: true
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t os-checker .

      - name: Run Docker
        run: docker run --env-file os-checker.env os-checker ./run.sh

      - name: List local images
        run: docker images --all && df -alh
