name: Github API

on: [push]

# env:
#   GH_TOKEN: ${{ github.token }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: gh api
        run: |
          gh auth status
          sh gh-api.sh
