name: Install Checkers

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always
  XZ_OPT: -e9
  TAG_PRECOMPILED_CHECKERS: cache-os-checker-v0.8.0.redb

jobs:
  install:
    runs-on: ubuntu-latest
    if: true
    steps:

      - name: Install AtomVChecker
        run: |
          git clone https://github.com/os-checker/atomicvchecker
          cd atomicvchecker/section-5-detection/AtomVChecker
          cargo install --path . --locked
          cargo atomicvchecker --help

      - name: Install cargo-updes
        run: cargo binstall --force -y cargo-udeps --locked && cargo udeps --version

      - name: Install cargo-outdated
        run: cargo binstall --force -y cargo-outdated && cargo outdated --version

      - name: Install cargo-semver-checks
        # run: cargo binstall --force -y cargo-semver-checks && cargo semver-checks --version
        # see https://github.com/obi1kenobi/cargo-semver-checks/issues/1068
        run: cargo install --git https://github.com/os-checker/cargo-semver-checks.git --branch "fix/--target" --locked cargo-semver-checks && cargo semver-checks --version

      - name: Install RAPx
        run: |
          git clone https://github.com/os-checker/RAPx.git
          cd RAPx
          git switch main
          cd rapx
          cargo install --path .
          cargo rapx --help

      - name: Install Rudra
        run: |
          git clone https://github.com/os-checker/Rudra.git
          cd Rudra
          git switch master
          cargo install --path . --locked
          cargo rudra --help

      - name: Install Mirai
        run: |
          git clone https://github.com/os-checker/MIRAI.git
          cd MIRAI
          git switch main
          cargo install --path checker --no-default-features -F z3,z3-sys --locked
          cargo mirai --help

      - name: Install Lockbud
        run: |
          git clone https://github.com/os-checker/lockbud.git
          cd lockbud
          git switch all
          cargo install --path .
          cargo lockbud --help

      - run: rustup default nightly

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-audit
        run: cargo binstall --force -y cargo-audit && cargo audit --version

      - name: Install cargo-geiger
        run: cargo binstall --force -y cargo-geiger && cargo geiger --version

      - name: Install cargo-nextest
        run: cargo binstall --force -y cargo-nextest && cargo nextest --version

      - name: Upload Precompiled Checkers to database
        run: |
          cd ~/.cargo/bin/
          ls -alh
          tar -cJf checkers.tar.xz rapx cargo-rapx lockbud cargo-lockbud mirai cargo-mirai rudra cargo-rudra cargo-binstall cargo-audit cargo-outdated cargo-geiger cargo-semver-checks cargo-nextest atomicvchecker cargo-atomicvchecker cargo-udeps
          gh release upload --clobber -R os-checker/database ${{ env.TAG_PRECOMPILED_CHECKERS }} checkers.tar.xz
