name: Install libudev

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    if: true
    steps:

    - run: sudo apt search libudev
    - run: sudo apt install libudev-dev -y
