name: Install Checkers

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always
  XZ_OPT: -e9

jobs:
  install:
    runs-on: ubuntu-latest
    if: false
    steps:

      - name: Install Rudra
        run: |
          git clone https://github.com/os-checker/Rudra.git
          cd Rudra
          git switch master
          cargo install --path . --locked
          cargo rudra --help

      - name: Install Mirai
        run: |
          git clone https://github.com/os-checker/MIRAI.git
          cd MIRAI
          git switch main
          cargo install --path checker --no-default-features -F z3,z3-sys --locked
          cargo mirai --help

      - name: Install Rap
        run: |
          git clone https://github.com/os-checker/RAP.git
          cd RAP
          git switch main
          cd rap
          cargo install --path .
          cargo rap --help

      - name: Install Lockbud
        run: |
          git clone https://github.com/os-checker/lockbud.git
          cd lockbud
          git switch all
          cargo install --path .
          cargo lockbud --help

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-audit
        run: cargo binstall --force -y cargo-audit && cargo audit --version

      - name: Install cargo-outdated
        run: cargo binstall --force -y cargo-outdated && cargo outdated --version

      - name: Install cargo-geiger
        run: cargo binstall --force -y cargo-geiger && cargo geiger --version

      - name: Install cargo-semver-checks
        run: cargo binstall --force -y cargo-semver-checks && cargo semver-checks --version

      - name: Upload Precompiled Checkers to database
        run: |
          cd ~/.cargo/bin/
          ls -alh
          tar -cJf checkers.tar.xz rap cargo-rap lockbud cargo-lockbud mirai cargo-mirai rudra cargo-rudra cargo-binstall cargo-audit cargo-outdated cargo-geiger cargo-semver-checks
          gh release upload --clobber -R os-checker/database precompiled-checkers checkers.tar.xz
