name: Install libfuse3-dev

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    if: true
    steps:
    # - run: sudo apt search fuse3
    - run: sudo apt install libfuse-dev fuse3 libfuse3-dev -y
    - run: |
        ls -alh /etc/fuse.conf
        cat /etc/fuse.conf
        sudo echo user_allow_other >> /etc/fuse.conf
        cat /etc/fuse.conf
    - uses: actions/checkout@v4
      with:
        repository: yuoo655/ext4libtest
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - name: clippy
      run: |
        cargo clippy
    - name: test
      run: |
        sudo sh gen_img.sh
        cargo run ./foo/
