name: Install libfuse3-dev

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    if: false
    steps:
    # - run: sudo apt search fuse3
    - run: sudo apt install libfuse-dev fuse3 libfuse3-dev -y
    - name: set user_allow_other in /etc/fuse.conf
      run: |
        sudo chmod +777 /etc/fuse.conf
        echo user_allow_other >> /etc/fuse.conf
    - uses: actions/checkout@v4
      with:
        repository: yuoo655/ext4libtest
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - name: clippy
      run: |
        cargo clippy
    - name: test
      run: |
        sudo sh gen_img.sh
        # cargo run ./foo/ # this need two terminals or a separate test
        cargo test
