name: Install Checkers

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    steps:

      - name: install mirai
        run: |
          git clone https://github.com/os-checker/MIRAI.git
          cd MIRAI
          git switch main
          cargo install --path checker --no-default-features -F z3,z3-sys
          cargo mirai --help

      - name: install rap
        run: |
          git clone https://github.com/os-checker/RAP.git
          cd RAP
          git switch main
          cd rap
          cargo install --path .
          cargo rap --help

      - name: install lockbud
        run: |
          git clone https://github.com/os-checker/lockbud.git
          cd lockbud
          git switch all
          cargo install --path .
          cargo lockbud --help

      - name: install rudra
        run: |
          git clone https://github.com/os-checker/Rudra.git
          cd Rudra
          git switch master
          cargo install --path .
          cargo rudra --help
