name: MIRAI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: os-checker/MIRAI

      - name: Install MIRIAI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/os-checker/MIRAI/releases/download/v1.1.9/mirai-installer.sh | sh

      - name: Set up Rust toolchain for MIRAI
        run: |
          rustup toolchain add nightly-2023-12-30 --profile minimal -c rust-src,rustc-dev,llvm-tools-preview,rustfmt,clippy
          rustup default nightly-2023-12-30

      - name: Run MIRAI
        run: |
          ls -alh $(which cargo-mirai)
          ls -alh $(which mirai)
          MIRAI_FLAGS=--diag=verify cargo mirai -p mirai-standard-contracts

