name: Run MIRAI With Docker Image

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: df -alh && free -h
      #
      # - name: Pull MIRAI Docker
      #   run: |
      #     docker pull zjpzjp/mirai:latest
      #     docker images -a

      ######## Local Image ########
      - name: Build Docker Image
        run: |
          docker build -t test .
          docker images -a

      - run: df -alh && free -h

      - name: Run Docker Image
        run: docker run test 

      - run: df -alh && free -h
