name: MIRAI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: kern-crates/rtc

      - name: Install MIRIAI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/os-checker/MIRAI/releases/download/v1.1.9/mirai-installer.sh | sh

      - name: Set up Rust toolchain for MIRAI
        run: |
          rustup toolchain add nightly-2023-12-30 --profile minimal -c rust-src,rustc-dev,llvm-tools-preview,rustfmt,clippy
          rustup component add clippy

      - name: Run MIRAI (--diag=paranoid)
        run: |
          ls -alh $(which cargo-mirai)
          ls -alh $(which mirai)
          time MIRAI_FLAGS="--diag=paranoid" cargo +nightly-2023-12-30 mirai
      - name: Run MIRAI Two More Times (Incrementally)
        run: |
          time MIRAI_FLAGS="--diag=paranoid" cargo +nightly-2023-12-30 mirai >/dev/null
          time MIRAI_FLAGS="--diag=paranoid" cargo +nightly-2023-12-30 mirai >/dev/null

      - name: Run MIRAI (--diag=library)
        run: |
          cargo clean
          time MIRAI_FLAGS="--diag=library" cargo +nightly-2023-12-30 mirai

      - name: Run MIRAI (--diag=verify)
        run: |
          cargo clean
          time MIRAI_FLAGS="--diag=verify" cargo +nightly-2023-12-30 mirai

      - name: Run MIRAI (--diag=default)
        run: |
          cargo clean
          time MIRAI_FLAGS="--diag=default" cargo +nightly-2023-12-30 mirai

      - name: Run MIRAI (--statistics)
        run: |
          cargo clean
          echo "--diag=paranoid"
          time MIRAI_FLAGS="--statistics --diag=paranoid" cargo +nightly-2023-12-30 mirai
          cargo clean
          echo "--diag=library"
          time MIRAI_FLAGS="--statistics --diag=library" cargo +nightly-2023-12-30 mirai
          cargo clean
          echo "--diag=verify"
          time MIRAI_FLAGS="--statistics --diag=verify" cargo +nightly-2023-12-30 mirai
          cargo clean
          echo "--diag=default"
          time MIRAI_FLAGS="--statistics --diag=default" cargo +nightly-2023-12-30 mirai

      - name: Run Clippy
        run: |
          cargo clean
          time cargo +nightly-2023-12-30 clippy
      - name: Run Clippy Two More Times (Incrementally)
        run: |
          time cargo +nightly-2023-12-30 clippy >/dev/null
          time cargo +nightly-2023-12-30 clippy >/dev/null
