name: Run MIRAI With Docker Image

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Pull MIRAI Docker
        run: |
          docker pull zjpzjp/mirai:latest
          docker images -a

      ######## Local Image ########
      - name: Build Docker Image
        run: docker build -t test .

      - name: Run Docker Image
        run: docker run test
