name: Run MIRAI With Docker Image

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull MIRAI Docker
        run: |
          docker pull zjpzjp/mirai:latest
          docker images -a

      - name: Run MIRAI
        run: docker run -v $(pwd):/ci -w /ci zjpzjp/mirai:latest "bash /ci/mirai.sh"
