name: Pull & Run os-checker docker

on: [push]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/os-checker:latest

jobs:
  install:
    runs-on: ubuntu-latest
    if: true
    steps:
      - uses: actions/checkout@v4

      - name: Pull os-checker docker
        run: docker pull ${{ env.IMAGE }}

      - name: List images
        run: docker images --all && df -alh

      - name: Run os-checker docker
        run: docker run -v "$PWD":/tmp/_pwd_ --env-file os-checker.env ${{ env.IMAGE }} /tmp/_pwd_/run.sh

