name: RAP

on: [push]

env:
  CARGO_TERM_COLOR: always
  # gh cli needs this token
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
   # cache.redb tag in database release
  TAG_CACHE: cache-v7.redb
  RAP_LOG: warn
  RAP_TOOLCHAIN: +nightly-2024-06-30

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: os-checker/RAP

      - name: Check Z3
        run: |
          sudo apt update && sudo apt-get install ripgrep -y 
          apt list --installed | rg "(z3)|(clang)"

      - name: Install rap
        run: |
          cd rap
          cargo install --path .
          gh release upload --clobber -R os-checker/database ${{ env.TAG_CACHE }} ~/.cargo/bin/cargo-rap ~/.cargo/bin/rap

      - name: Test
        run: |
          cargo ${{ env.RAP_TOOLCHAIN }} rap -help
          cd tests/uaf_drop
          cargo ${{ env.RAP_TOOLCHAIN }} rap -F

      - name: Test os-checker-test-suite
        run: |
          cd ~
          git clone https://github.com/os-checker/os-checker-test-suite.git
          cd os-checker-test-suite/rap-checks-this
          cargo ${{ env.RAP_TOOLCHAIN }} rap -F

      - name: cargo-audit
        run: |
          cargo audit --version # built in GA; should be greater than v0.21
          cargo install cargo-audit --version 0.21.0-rc.0 --force
          gh release upload --clobber -R os-checker/database ${{ env.TAG_CACHE }} ~/.cargo/bin/cargo-audit

      - name: View ~/.cargo/bin/
        run: ls -alh ~/.cargo/bin/
