name: Publish Rudra

on: [push]

env:
  CARGO_TERM_COLOR: always
  # gh cli needs this token
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
   # cache.redb tag in database release
  TAG_CACHE: cache-v7.redb
  REBUILD: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: os-checker/os-checker-test-suite

      - name: install rudra
        if: ${{ env.REBUILD == 'true' }}
        run: |
          cd ~
          git clone https://github.com/os-checker/Rudra.git
          cd Rudra
          # git switch os-checker
          # rm rust-toolchain
          cargo install --path .
          cd ~/.cargo/bin
          gh release upload --clobber -R os-checker/database ${{ env.TAG_CACHE }} cargo-rudra rudra

      - name: download rudra
        if: ${{ env.REBUILD != 'true' }}
        run: |
          gh release download --clobber -R os-checker/database ${{ env.TAG_CACHE }} -p cargo-rudra -p rudra -D ~/.cargo/bin
          chmod +x ~/.cargo/bin/rudra
          chmod +x ~/.cargo/bin/cargo-rudra

      # - name: run check 
      #   run: |
      #     cd ~
      #     git clone https://github.com/os-checker/os-checker-test-suite
      #     cd os-checker-test-suite
      #     cargo geiger
      #     cd workspace2/crates/ws-lockbud-checks-this1
      #     echo "geiger by default (with emoji)"
      #     cargo geiger
      #     echo "geiger with Ascii chars"
      #     cargo geiger --output-format Ascii
