name: Rust Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Test
      run: |
        cd crates/duct-test
        cargo r
        ls -alh $(which mirai)
