name: semver-checks Cargo fix

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    if: false
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["nightly-2025-01-01", "nightly-2025-01-12"]
    steps:
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}

    - run: rustup -Vv
    - run: rustc -Vv
    - run: cargo -Vv

    - name: arm_gicv2
      run: |
        cd && git clone https://github.com/arceos-org/arm_gicv2.git && cd arm_gicv2
        rustup target add aarch64-unknown-none

    - name: cargo check --target aarch64-unknown-none
      run: cd ~/arm_gicv2 && cargo check --target aarch64-unknown-none

    - name: RUSTFLAGS=-Dwarnings cargo check --target aarch64-unknown-none
      if: ${{ always() }}
      run: cd ~/arm_gicv2 && RUSTFLAGS=-Dwarnings cargo check --target aarch64-unknown-none

    - name: RUSTFLAGS="-Awarnings -Dwarnings" cargo check --target aarch64-unknown-none
      if: ${{ always() }}
      run: cd ~/arm_gicv2 && RUSTFLAGS="-Awarnings -Dwarnings" cargo check --target aarch64-unknown-none

    - name: RUSTFLAGS="-Dwarnings -Awarnings" cargo check --target aarch64-unknown-none
      if: ${{ always() }}
      run: cd ~/arm_gicv2 && RUSTFLAGS="-Dwarnings -Awarnings" cargo check --target aarch64-unknown-none

    - name: install cargo-semver-checks
      if: ${{ always() }}
      run: cargo install --git https://github.com/obi1kenobi/cargo-semver-checks.git cargo-semver-checks

    - name: cargo semver-checks --target aarch64-unknown-none
      if: ${{ always() }}
      run: cd ~/arm_gicv2 && cargo semver-checks --target aarch64-unknown-none
