name: Test semver-checks fork

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    if: true
    steps:
    # - run: sudo apt search fuse3
    # - run: sudo apt install libfuse-dev fuse3 libfuse3-dev -y
    - uses: dtolnay/rust-toolchain@nightly
      # with:
      #   components: clippy

    - run: rustup -Vv
    - run: rustc -Vv
    - run: cargo -Vv

    - uses: actions/checkout@v4
      with:
        repository: obi1kenobi/cargo-semver-checks

    - name: install
      # run: cargo install --path . cargo-semver-checks
      run: |
        gh release download --clobber -R os-checker/database precompiled-checkers -p checkers.tar.xz
        tar -xvJf checkers.tar.xz -C ~/.cargo/bin/
        cargo semver-checks --version

    - name: test
      run: |
        rustup target add aarch64-unknown-none
        cd && gh repo clone Azure-stars/kernel_elf_parser && cd kernel_elf_parser
        cargo +nightly semver-checks --target aarch64-unknown-none
        cargo +nightly semver-checks --target x86_64-unknown-linux-gnu
