name: Test

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    if: true
    steps:

      - name: Download checkers.tar.xz
        run: gh release download --clobber -R os-checker/database precompiled-checkers -p checkers.tar.xz

      - name: Extract checkers.tar.xz
        run: |
          mkdir checkers
          tar -xvJf checkers.tar.xz -C checkers

      - name: View and Move to ~/.cargo/bin/
        run: |
          ls -alh checkers
          mv checkers/* ~/.cargo/bin/

      - name: Test usability
        run: |
          cargo audit --version
          cargo outdated --version
          cargo geiger --version

      - name: Test rudra
        run: rustup default nightly-2021-10-21 && cargo rudra --help

      - name: Test mirai
        run: rustup default nightly-2024-02-05 && cargo mirai --help

      - name: Test lockbud
        run: rustup default nightly-2024-10-05 && cargo lockbud --help

      - name: Test rap
        run: rustup default nightly-2024-10-12 && cargo rap --help

