name: Test docker

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    if: true
    steps:
      - uses: actions/checkout@v4

      - name: Prepare config JSONs
        run: |
          sudo mkdir /check && sudo chmod -R 777 /check && cd /check
          echo '{"os-checker/os-checker-test-suite":{}}' >repos.json

      - run: docker build -t test test.dockerfile

      - run: docker run -v /check:/check test

